spring.application.name=pi
spring.datasource.url=jdbc:mysql://localhost:3306/pi1?createDatabaseifNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8089
server.servlet.context-path=/pi

# Configuration pour envoi de mail avec Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= nader123mb456@gmail.com
spring.mail.password= jzcfkqsqtiuvikxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



