spring.application.name=pidb
spring.datasource.url=jdbc:mysql://localhost:3306/pidb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8089
server.servlet.context-path=/pidb


# Configuration pour envoi de mail avec Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= chaimaakermi98@gmail.com
spring.mail.password= cjyb pkmd blak mijm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true