spring.config.import=optional:classpath:env.properties


# General App Config
spring.application.name=CloudiniPi
server.port=8087
server.servlet.context-path=/pi

# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/pidb?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Disable security auto-config (if needed)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Email Configuration (SMTP)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=895f3d001@smtp-brevo.com
spring.mail.password=xsmtpsib-0b012ff630c7f2341d400ff8fe93be60f546b24b9d08102a44b7a45e6eb48692-6KvqXWRhJS48QIzt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Logging Email Sending
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# App URL
app.base-url=http://localhost:4200
app.reset-password.expiration=24
brevo.sender.email=foudhailimahdi5@gmail.com
app.base.url=http://localhost:8087

# Google AI API
google.ai.api.key=${GOOGLE_AI_API_KEY}

# Twilio
twilio.account.sid=${TWILIO_ACCOUNT_SID}
auth_token=${TWILIO_AUTH_TOKEN}
from_number=${TWILIO_FROM_NUMBER}

# Stripe
stripe.secret.key=${STRIPE_SECRET_KEY}


# AI Services (Python Flask)
python.service.url=http://localhost:5000/categorize
python.emotion.service.url=http://localhost:5000/detect-emotion

#Blog
app.upload.temp-dir=temp-uploads/
# src/main/resources/application.properties
gemini.api.key=AIzaSyB7tkE5DFgCdMHRfW2PdZEmzhLeY9fT0KU
spring.web.resources.static-locations=classpath:/static/,file:uploads/

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
#endBlog

# Metrics / Monitoring
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true

# Multipart upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson Hibernate lazy proxy workaround
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jackson.serialization.fail-on-empty-beans=false

# Spring Boot Actuator Prometheus (optional)
management.endpoint.prometheus.enabled=true


recaptcha.secret=6Ld-Xh0rAAAAAIHlk5VfUlUEkNLvla57fbtT4YV8
recaptcha.url=https://www.google.com/recaptcha/api/siteverify

google.client-id=549477820375-9rt1vpu7eauf1m6v42mfdf899umiq3ls.apps.googleusercontent.com


